package model;

public class StopWords {
	// Stop vardu saraksts
	private static String[] stopWordArray = { "aiz", "ap", "apakð", "ârpus",
			"augðpus", "bez", "caur",
			"dçï",
			"gar",
			"iekð",
			"iz",
			"kopð",
			"labad",
			"lejpus",
			"lîdz",
			"no",
			"otrpus",
			"pa",
			"par",
			"pâr",
			"pçc",
			"pie",
			"pirms",
			"pret",
			"priekð",
			"starp",
			"ðaipus",
			"uz",
			"viòpus",
			"virs",
			"virspus",
			"zem",
			"apakðpus",
			"kuri",
			"ðâdu",

			// Conjuctions
			"un",
			"bet",
			"jo",
			"ja",
			"ka",
			"lai",
			"vai",
			"arî",
			"kamçr",
			"nekâ",
			"tomçr",
			"tikko",
			"turpretî",
			"turpretim",
			"arî",
			"kaut",
			"gan",
			"tâdçï",
			"tâ",
			"ne",
			"tikvien",
			"vien",
			"kâ",
			"ir",
			"te",
			"kamçr",
			// Particles
			"ar", "diezin", "droði", "diemþçl", "nebût", "ik", "it", "taèu",
			"nu", "pat", "tiklab", "iekðpus", "nedz", "tik", "nevis",
			"turpretim", "jeb", "iekam", "iekâm",
			"iekâms",
			"kolîdz",
			"lîdzko",
			"tiklîdz",
			"jebðu",
			"tâlab",
			"tâpçc",
			"nekâ",
			"itin",
			"jâ",
			"jau",
			"jel",
			"nç",
			"nezin",
			"tad",
			"tikai",
			"vis",
			"tak",
			"iekams",
			"vien",
			// Modal verbs
			"bût", "biju", "biji", "bija", "bijâm", "bijât", "esmu", "esi",
			"esam", "esat", "bûðu", "bûsi", "bûs", "bûsim", "bûsiet", "tikt",
			"tiku", "tiki", "tika", "tikâm", "tikât", "tieku", "tiec", "tiek",
			"tiekam", "tiekat", "tikðu", "tiks", "tiksim", "tiksiet", "tapt",
			"tapi", "tapât", "topat", "tapðu", "tapsi", "taps", "tapsim",
			"tapsiet", "kïût", "kïuvu", "kïuvi", "kïuva",
			"kïuvâm",
			"kïuvât",
			"kïûstu",
			"kïûsti",
			"kïûst",
			"kïûstam",
			"kïûstat",
			"kïûðu",
			"kïûsi",
			"kïûs",
			"kïûsim",
			"kïûsiet",
			// verbs
			"varçt", "varçju", "varçjâm",
			"varçðu",
			"varçsim",
			"var",
			"varçji",
			"varçjât",
			"varçsi",
			"varçsiet",
			"varat",
			"varçja",
			"varçs",
			// more
			"bûtu", "kuras", "diez", "viss", "vismaz", "kas", "viòð", "daudz",
			"tâm", "ir", "tâdas", "viòi", "tas", "to", "nav", "mûs", "viòus",
			"viòiem", "tiem", "tie", "tâs", "ko", "ðiem", "kad", "vçl",
			"ðâ",
			"viòam",
			"tagad",
			"ðîm",
			"viòu",
			"ðim",
			"kuri",
			// Pronoun
			"es", "tu", "viòð", "viòa", "mçs", "jûs", "viòi", "viòas", "sevis",
			"mans", "tavs", "savs", "mançjs", "tavçjs", "savçjs", "mûsçjs",
			"jûsçjs", "viòçjs", "ðîs", "ðî", "tas", "tâ", "ðâds", "ðâda",
			"tâds", "tâda", "viòð", "viòa", "kas", "kurð", "kâds", "kas",
			"kurð", "kâds", "daþs", "cits", "kaut", "diez", "diezin", "nez",
			"nezin", "jebkas", "jebkurð", "jebkâds", "viss", "pats", "katrs",
			"ikkatrs", "jebkurð", "jebkâds", "ikviens", "abi", "abas", "nekas",
			"nekâds", "neviens", "kuros", "visa", "visu", "visiem" };

	public static boolean isStopWord(String word) {
		for (int i = 0; i < stopWordArray.length; i++) {
			if (stopWordArray[i].equals(word)) {
				return true;
			}
		}

		return false;
	}
}
